server:
  port: 8080
  shutdown: graceful
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://jhs512-medium-db.internal:5432/postgres
    username: postgres
    password: UWeivqZNNqSjczT
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.ll.medium: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    cookieDomain: "${custom.production.cookieDomain}"
    frontUrl: "${custom.production.frontUrl}"
    backUrl: "${custom.production.backUrl}"